# Generated by Django 4.2.7 on 2024-01-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_user_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
