# Generated by Django 4.2.7 on 2024-01-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publish', 'Может опубликовать'), ('set_description', 'Может изменить описание')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
